"""
dashboard/services/forecast_service.py - AQI Forecast service interface.

Provides multi-step ahead AQI predictions generated by the VAYU-DRISHTI ML pipeline.
Forecast data includes confidence intervals, feature importance, and model metadata.

Day 3: Replace stub bodies with APIClient.get() calls.
       On any APIError, returns stub data.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Any

import streamlit as st

from dashboard.services.api_client import APIClient, APIError


@dataclass
class ForecastStep:
    """A single time step in an AQI forecast sequence."""
    forecast_at: datetime
    predicted_aqi: float
    lower_bound: float
    upper_bound: float
    aqi_category: str


@dataclass
class ModelMetrics:
    """Validation metrics for the active forecast model."""
    model_name: str
    model_version: str
    rmse: float
    mae: float
    r_squared: float
    training_date: str
    validation_period: str


_STUB_METRICS = ModelMetrics(
    model_name="VAYU-DRISHTI XGBoost v1",
    model_version="stub-day2",
    rmse=18.4,
    mae=12.7,
    r_squared=0.84,
    training_date="N/A",
    validation_period="N/A",
)

_STUB_FEATURE_IMPORTANCES = [
    {"feature": "PM2.5 (t-1)", "importance": 0.34},
    {"feature": "Wind Speed", "importance": 0.18},
    {"feature": "Temperature", "importance": 0.15},
    {"feature": "NO2", "importance": 0.12},
    {"feature": "Humidity", "importance": 0.11},
    {"feature": "HCHO", "importance": 0.10},
]


def _station_id_from_label(selected: str | None) -> str:
    """Map dashboard station labels to backend IDs without depending on dash glyphs."""
    label = selected or ""
    if "Mumbai" in label:
        return "MU001"
    if "Bengaluru" in label:
        return "BL001"
    if "Hyderabad" in label:
        return "HY001"
    return "DL001"


def _build_stub_forecast(station_id: str, horizon_hours: int) -> list[dict[str, Any]]:
    """Build deterministic fallback forecast steps when the API is unavailable."""
    baselines = {
        "DL001": 312.0,
        "MU001": 127.0,
        "BL001": 88.0,
        "HY001": 51.0,
    }
    base = baselines.get(station_id, 140.0)
    now = datetime.utcnow().replace(minute=0, second=0, microsecond=0)
    steps: list[dict[str, Any]] = []

    for hour in range(1, horizon_hours + 1):
        forecast_time = now + timedelta(hours=hour)
        diurnal = 18.0 if 7 <= forecast_time.hour <= 10 else 0.0
        evening = 12.0 if 18 <= forecast_time.hour <= 22 else 0.0
        trend = -0.18 * hour
        predicted = max(25.0, min(500.0, base + diurnal + evening + trend))
        spread = 12.0 + (hour * 0.35)
        category = (
            "Good" if predicted <= 50 else
            "Satisfactory" if predicted <= 100 else
            "Moderate" if predicted <= 200 else
            "Poor" if predicted <= 300 else
            "Very Poor" if predicted <= 400 else
            "Severe"
        )
        steps.append(
            {
                "forecast_at": forecast_time.isoformat(),
                "predicted_aqi": round(predicted, 1),
                "lower_bound": round(max(0.0, predicted - spread), 1),
                "upper_bound": round(min(500.0, predicted + spread), 1),
                "aqi_category": category,
            }
        )

    return steps


class ForecastService:
    """Fetches AQI forecast data and model metadata."""

    def __init__(self, client: APIClient | None = None) -> None:
        self._client = client or APIClient()

    def _get_selected_station_id(self) -> str:
        """Map selected station in session state to station_id."""
        return _station_id_from_label(st.session_state.get("fc_station"))

@st.cache_data(ttl=60)
def _get_station_forecast_cached(station_id: str, horizon_hours: int) -> list[dict[str, Any]]:
    """Perform the actual API call for forecast, cached for 60 seconds."""
    client = APIClient()
    try:
        resp = client.get(
            "/forecast",
            params={"station_id": station_id, "horizon_hours": horizon_hours},
        )
        return resp.data.get("steps", [])
    except APIError:
        return []


@st.cache_data(ttl=300)
def _get_model_metrics_cached(station_id: str) -> dict[str, Any]:
    """Fetch model metrics from API, cached for 5 minutes."""
    client = APIClient()
    try:
        resp = client.get("/forecast", params={"station_id": station_id})
        return resp.data.get("model_metrics", {})
    except APIError:
        return {}


@st.cache_data(ttl=300)
def _get_feature_importances_cached(station_id: str) -> list[dict[str, Any]]:
    """Fetch feature importances from API, cached for 5 minutes."""
    client = APIClient()
    try:
        resp = client.get("/forecast", params={"station_id": station_id})
        features = resp.data.get("feature_importances", [])
        if not features:
            return _STUB_FEATURE_IMPORTANCES
        return [
            {"feature": f["feature"], "importance": f["importance"]}
            for f in features
        ]
    except APIError:
        return _STUB_FEATURE_IMPORTANCES


class ForecastService:
    """Fetches AQI forecast data and model metadata."""

    def __init__(self, client: APIClient | None = None) -> None:
        self._client = client or APIClient()

    def _get_selected_station_id(self) -> str:
        """Map selected station in session state to station_id."""
        return _station_id_from_label(st.session_state.get("fc_station"))

    def get_station_forecast(
        self,
        station_id: str,
        horizon_hours: int = 72,
    ) -> list[ForecastStep]:
        """Return multi-step AQI forecast for a monitoring station."""
        raw_steps = _get_station_forecast_cached(station_id, horizon_hours)
        if not raw_steps:
            raw_steps = _build_stub_forecast(station_id, horizon_hours)

        try:
            return [
                ForecastStep(
                    forecast_at=datetime.fromisoformat(step["forecast_at"].replace("Z", "+00:00")),
                    predicted_aqi=step["predicted_aqi"],
                    lower_bound=step["lower_bound"],
                    upper_bound=step["upper_bound"],
                    aqi_category=step["aqi_category"],
                )
                for step in raw_steps
            ]
        except (KeyError, TypeError, ValueError):
            fallback_steps = _build_stub_forecast(station_id, horizon_hours)
            return [
                ForecastStep(
                    forecast_at=datetime.fromisoformat(step["forecast_at"]),
                    predicted_aqi=step["predicted_aqi"],
                    lower_bound=step["lower_bound"],
                    upper_bound=step["upper_bound"],
                    aqi_category=step["aqi_category"],
                )
                for step in fallback_steps
            ]

    def get_model_metrics(self) -> ModelMetrics:
        """Return accuracy metrics of the active forecast model."""
        station_id = self._get_selected_station_id()
        m = _get_model_metrics_cached(station_id)
        if not m:
            return _STUB_METRICS
        return ModelMetrics(
            model_name=m.get("model_name", "VAYU-DRISHTI XGBoost v1"),
            model_version=m.get("model_version", "1.0.0"),
            rmse=m.get("rmse", 18.4),
            mae=m.get("mae", 12.7),
            r_squared=m.get("r_squared", 0.84),
            training_date=m.get("training_date", "N/A"),
            validation_period=m.get("validation_period", "N/A"),
        )

    def get_feature_importances(self) -> list[dict[str, Any]]:
        """Return top features driving the AQI forecast model."""
        station_id = self._get_selected_station_id()
        return _get_feature_importances_cached(station_id)


forecast_service = ForecastService()