"""
dashboard/services/forecast_service.py — AQI Forecast service interface.

Provides multi-step ahead AQI predictions generated by the VAYU-DRISHTI ML pipeline.
Forecast data includes confidence intervals, feature importance, and model metadata.

Day 3: Replace stub bodies with APIClient.get() calls.
       On any APIError, returns stub data.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any
import streamlit as st

from dashboard.services.api_client import APIClient, APIError


@dataclass
class ForecastStep:
    """A single time step in an AQI forecast sequence."""
    forecast_at: datetime
    predicted_aqi: float
    lower_bound: float              # 5th percentile confidence interval
    upper_bound: float              # 95th percentile confidence interval
    aqi_category: str


@dataclass
class ModelMetrics:
    """Validation metrics for the active forecast model."""
    model_name: str
    model_version: str
    rmse: float
    mae: float
    r_squared: float
    training_date: str
    validation_period: str


# ── Fallback stub data ─────────────────────────────────────────────────────────

_STUB_METRICS = ModelMetrics(
    model_name="VAYU-DRISHTI XGBoost v1",
    model_version="stub-day2",
    rmse=18.4,
    mae=12.7,
    r_squared=0.84,
    training_date="N/A",
    validation_period="N/A",
)

_STUB_FEATURE_IMPORTANCES = [
    {"feature": "PM2.5 (t-1)", "importance": 0.34},
    {"feature": "Wind Speed",   "importance": 0.18},
    {"feature": "Temperature",  "importance": 0.15},
    {"feature": "NO2",          "importance": 0.12},
    {"feature": "Humidity",     "importance": 0.11},
    {"feature": "HCHO",         "importance": 0.10},
]

_STATION_MAP = {
    "Delhi – Anand Vihar": "DL001",
    "Mumbai – Bandra Kurla": "MU001",
    "Bengaluru – Silk Board": "BL001",
}


class ForecastService:
    """Fetches AQI forecast data and model metadata."""

    def __init__(self, client: APIClient | None = None) -> None:
        self._client = client or APIClient()

    def _get_selected_station_id(self) -> str:
        """Map selected station in session state to station_id."""
        selected = st.session_state.get("fc_station")
        return _STATION_MAP.get(selected, "DL001")

    @st.cache_data(ttl=60)
    def _get_station_forecast_cached(_self, station_id: str, horizon_hours: int) -> list[ForecastStep]:
        """Perform the actual API call for forecast, cached for 60 seconds."""
        try:
            resp = _self._client.get(
                "/forecast",
                params={"station_id": station_id, "horizon_hours": horizon_hours}
            )
            raw_steps = resp.data.get("steps", [])
            return [
                ForecastStep(
                    forecast_at=datetime.fromisoformat(
                        step["forecast_at"].replace("Z", "+00:00")
                    ),
                    predicted_aqi=step["predicted_aqi"],
                    lower_bound=step["lower_bound"],
                    upper_bound=step["upper_bound"],
                    aqi_category=step["aqi_category"],
                )
                for step in raw_steps
            ]
        except APIError:
            return []

    def get_station_forecast(
        self,
        station_id: str,
        horizon_hours: int = 72,
    ) -> list[ForecastStep]:
        """
        Return multi-step AQI forecast for a monitoring station.

        Calls the cached private method.
        """
        return self._get_station_forecast_cached(station_id, horizon_hours)

    @st.cache_data(ttl=300)
    def _get_model_metrics_cached(_self, station_id: str) -> ModelMetrics:
        """Fetch model metrics from API, cached for 5 minutes."""
        try:
            resp = _self._client.get("/forecast", params={"station_id": station_id})
            m = resp.data.get("model_metrics", {})
            return ModelMetrics(
                model_name=m.get("model_name", "VAYU-DRISHTI XGBoost v1"),
                model_version=m.get("model_version", "1.0.0"),
                rmse=m.get("rmse", 18.4),
                mae=m.get("mae", 12.7),
                r_squared=m.get("r_squared", 0.84),
                training_date=m.get("training_date", "—"),
                validation_period=m.get("validation_period", "—"),
            )
        except APIError:
            return _STUB_METRICS

    def get_model_metrics(self) -> ModelMetrics:
        """
        Return accuracy metrics of the active forecast model.

        Calls the cached private method.
        """
        station_id = self._get_selected_station_id()
        return self._get_model_metrics_cached(station_id)

    @st.cache_data(ttl=300)
    def _get_feature_importances_cached(_self, station_id: str) -> list[dict[str, Any]]:
        """Fetch feature importances from API, cached for 5 minutes."""
        try:
            resp = _self._client.get("/forecast", params={"station_id": station_id})
            features = resp.data.get("feature_importances", [])
            if not features:
                return _STUB_FEATURE_IMPORTANCES
            return [
                {"feature": f["feature"], "importance": f["importance"]}
                for f in features
            ]
        except APIError:
            return _STUB_FEATURE_IMPORTANCES

    def get_feature_importances(self) -> list[dict[str, Any]]:
        """
        Return top features driving the AQI forecast model.

        Calls the cached private method.
        """
        station_id = self._get_selected_station_id()
        return self._get_feature_importances_cached(station_id)


forecast_service = ForecastService()
