"""
dashboard/services/forecast_service.py — AQI Forecast service interface.

Provides multi-step ahead AQI predictions generated by the VAYU-DRISHTI ML pipeline.
Forecast data includes confidence intervals, feature importance, and model metadata.

Day 2: All methods return typed stub data.
Day 3: Replace stub bodies with APIClient.get() calls.

API endpoints this service will consume (Day 3+):
  GET /api/v1/forecast/aqi          — 24/48/72-hour AQI forecast for a station
  GET /api/v1/forecast/regional     — Regional AQI forecast map grid
  GET /api/v1/forecast/accuracy     — Model performance metrics (RMSE, MAE, R²)
  GET /api/v1/forecast/features     — Top feature importances driving the forecast
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any

from dashboard.services.api_client import APIClient


@dataclass
class ForecastStep:
    """A single time step in an AQI forecast sequence."""
    forecast_at: datetime
    predicted_aqi: float
    lower_bound: float              # 5th percentile confidence interval
    upper_bound: float              # 95th percentile confidence interval
    aqi_category: str


@dataclass
class ModelMetrics:
    """Validation metrics for the active forecast model."""
    model_name: str
    model_version: str
    rmse: float
    mae: float
    r_squared: float
    training_date: str
    validation_period: str


class ForecastService:
    """Fetches AQI forecast data and model metadata."""

    def __init__(self, client: APIClient | None = None) -> None:
        self._client = client or APIClient()

    def get_station_forecast(
        self,
        station_id: str,
        horizon_hours: int = 72,
    ) -> list[ForecastStep]:
        """
        Return multi-step AQI forecast for a monitoring station.

        Day 2: Returns empty list (no ML model yet).
        Day 3: resp = self._client.get(f"/forecast/aqi", params={"station_id": station_id, "hours": horizon_hours})
        """
        return []

    def get_model_metrics(self) -> ModelMetrics:
        """
        Return accuracy metrics of the active forecast model.

        Day 2: Returns stub metrics.
        Day 3: resp = self._client.get("/forecast/accuracy")
        """
        return ModelMetrics(
            model_name="VAYU-DRISHTI XGBoost v1",
            model_version="stub-day2",
            rmse=18.4,
            mae=12.7,
            r_squared=0.84,
            training_date="N/A",
            validation_period="N/A",
        )

    def get_feature_importances(self) -> list[dict[str, Any]]:
        """
        Return top features driving the AQI forecast model.

        Day 2: Returns stub feature list.
        Day 3: resp = self._client.get("/forecast/features")
        """
        return [
            {"feature": "PM2.5 (t-1)", "importance": 0.34},
            {"feature": "Wind Speed",   "importance": 0.18},
            {"feature": "Temperature",  "importance": 0.15},
            {"feature": "NO2",          "importance": 0.12},
            {"feature": "Humidity",     "importance": 0.11},
            {"feature": "HCHO",         "importance": 0.10},
        ]


forecast_service = ForecastService()
