import logging
import json
from pathlib import Path
from typing import Any, Dict, Union

import pandas as pd
import numpy as np
import joblib

try:
    from data_collection_pipeline import config
except ImportError:
    config = None

logger = logging.getLogger(__name__)


def load_production_model(workspace_dir: Union[str, Path]) -> Any:
    """Loads the serialized production model."""
    logger.info("Loading production model.")
    model_path = Path(workspace_dir) / "production_model.joblib"
    
    if not model_path.exists():
        logger.error(f"Production model not found at {model_path}")
        raise FileNotFoundError(f"Missing {model_path}")
        
    model = joblib.load(model_path)
    logger.info(f"Loaded production model from {model_path}")
    return model


def load_input_dataset(file_path: Union[str, Path]) -> pd.DataFrame:
    """Loads the input dataset for inference."""
    logger.info(f"Loading input dataset from {file_path}")
    path = Path(file_path)
    if not path.exists():
        logger.error(f"Input dataset not found at {path}")
        raise FileNotFoundError(f"Missing {path}")
        
    df = pd.read_csv(path)
    logger.info(f"Loaded input dataset with shape {df.shape}")
    return df


def prepare_inference_features(df: pd.DataFrame, target_column: str = "PM2.5") -> pd.DataFrame:
    """Prepares numerical features for inference."""
    logger.info("Preparing features for inference.")
    numeric_df = df.select_dtypes(include=["number"]).copy()
    if target_column in numeric_df.columns:
        numeric_df = numeric_df.drop(columns=[target_column])
    # For inference, assume we handle NaNs simply. In a real scenario, an imputer object would be loaded.
    numeric_df = numeric_df.fillna(numeric_df.mean(numeric_only=True)).fillna(0.0)
    logger.info(f"Prepared inference features shape: {numeric_df.shape}")
    return numeric_df


def run_inference(model: Any, X: pd.DataFrame) -> np.ndarray:
    """Runs predictions using the production model."""
    logger.info("Executing model inference.")
    predictions = model.predict(X)
    logger.info(f"Generated {len(predictions)} predictions.")
    return predictions


def export_predictions(df: pd.DataFrame, predictions: np.ndarray, output_dir: Union[str, Path]) -> pd.DataFrame:
    """Combines inputs and predictions, then exports them."""
    logger.info("Exporting predictions.")
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    result_df = df.copy()
    result_df["Predicted_Target"] = predictions
    
    csv_path = out_path / "predictions.csv"
    result_df.to_csv(csv_path, index=False)
    logger.info(f"Predictions saved to {csv_path}")
    
    return result_df


def generate_inference_report(result_df: pd.DataFrame, output_dir: Union[str, Path]) -> None:
    """Generates the inference summary JSON and Markdown report."""
    logger.info("Generating inference reports.")
    out_path = Path(output_dir)
    
    preds = result_df["Predicted_Target"]
    summary = {
        "Total_Samples": len(preds),
        "Mean_Prediction": float(np.mean(preds)),
        "Min_Prediction": float(np.min(preds)),
        "Max_Prediction": float(np.max(preds)),
        "Std_Prediction": float(np.std(preds, ddof=1) if len(preds) > 1 else 0.0)
    }
    
    json_path = out_path / "prediction_summary.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4)
        
    md_path = out_path / "inference_report.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("# Team RAPTORS - Inference Report\n\n")
        f.write("## Overview\n")
        f.write("This report provides a summary of predictions generated by the production model on new input data.\n\n")
        
        f.write("## Prediction Summary\n")
        f.write(f"- **Total Samples Processed**: {summary['Total_Samples']}\n")
        f.write(f"- **Mean Prediction**: {summary['Mean_Prediction']:.4f}\n")
        f.write(f"- **Min Prediction**: {summary['Min_Prediction']:.4f}\n")
        f.write(f"- **Max Prediction**: {summary['Max_Prediction']:.4f}\n")
        f.write(f"- **Standard Deviation**: {summary['Std_Prediction']:.4f}\n\n")
        
        f.write("## Sample Output\n")
        f.write("Below are the first 10 predictions along with their features.\n\n")
        
        # Display the first 10 rows
        sample_df = result_df.head(10)
        # Select a few columns for display so it fits well in Markdown
        display_cols = [c for c in sample_df.columns if c != "Predicted_Target"][:5] + ["Predicted_Target"]
        
        f.write("| " + " | ".join(display_cols) + " |\n")
        f.write("|" + "|".join([":---:"] * len(display_cols)) + "|\n")
        
        for _, row in sample_df.iterrows():
            row_vals = []
            for col in display_cols:
                val = row[col]
                if isinstance(val, (int, float)):
                    row_vals.append(f"{val:.4f}")
                else:
                    row_vals.append(str(val))
            f.write("| " + " | ".join(row_vals) + " |\n")
            
        f.write("\n")
        
    logger.info("Inference reports generated successfully.")


def run_pipeline(workspace_dir: Union[str, Path], input_filename: str = "test_dataset.csv") -> None:
    """Executes the complete inference pipeline."""
    logger.info("Starting inference pipeline.")
    
    workspace_path = Path(workspace_dir)
    model = load_production_model(workspace_path)
    
    # We use test_dataset.csv as a proxy for "new input dataset" if not explicitly provided
    input_path = workspace_path / input_filename
    if not input_path.exists():
        input_path = workspace_path / "train_dataset.csv"
        logger.warning(f"Default input not found, falling back to {input_path.name}")
        
    df = load_input_dataset(input_path)
    
    target_col = "PM2.5"
    if config and hasattr(config, "REQUIRED_TARGET_COLUMN"):
        target_col = getattr(config, "REQUIRED_TARGET_COLUMN")
        
    if target_col not in df.columns and "PM2.5" in df.columns:
        target_col = "PM2.5"
        
    X = prepare_inference_features(df, target_col)
    
    predictions = run_inference(model, X)
    result_df = export_predictions(df, predictions, workspace_path)
    
    generate_inference_report(result_df, workspace_path)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="[%(asctime)s] %(levelname)s [%(name)s] - %(message)s")
    workspace_root = Path(__file__).resolve().parent.parent.parent
    run_pipeline(workspace_dir=workspace_root)
