"""
GET /api/v1/forecast — AQI Forecast endpoint.

Returns a multi-step ahead AQI forecast for a single monitoring station
along with model performance metrics and feature importances.

The VAYU-DRISHTI XGBoost ensemble predicts AQI at 1-hour intervals for
up to 72 hours, with calibrated 5th/95th percentile confidence intervals.
Feature importances are global (averaged across all training predictions).

Design decisions:
  - station_id is a required query param (not a path param) to avoid
    implicit 404 responses when the client forgets to supply it.
    Explicit 422 validation error is clearer than a 404 for the caller.
  - Full ForecastResponse includes model_metrics and feature_importances
    to support single-request rendering of the forecast + model panel.
  - horizon_hours is capped at 72 — beyond this the forecast uncertainty
    is too wide to be scientifically useful for AQI prediction.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, Query, status
from fastapi.concurrency import run_in_threadpool

from app.core.exceptions import NotFoundError
from app.core.logging import get_logger
from app.schemas.forecast import ForecastResponse
from app.services.forecast_service import ForecastService, forecast_service

logger = get_logger(__name__)
router = APIRouter()

# Known station IDs (Day 3 stub check; replace with DB lookup in Day N)
_KNOWN_STATIONS = {"DL001", "MU001", "BL001", "HY001", "CH001", "KO001", "PU001", "AH001"}


@router.get(
    "/forecast",
    response_model=ForecastResponse,
    summary="AQI Station Forecast",
    description=(
        "Returns a multi-step ahead AQI forecast for a single CPCB monitoring station. "
        "Predictions are generated by the VAYU-DRISHTI XGBoost ensemble at 1-hour intervals "
        "for the requested horizon (up to 72 hours). "
        "Each forecast step includes a **point prediction** (50th percentile) and "
        "**confidence bounds** (5th and 95th percentile quantiles). "
        "The response also includes **model performance metrics** (RMSE, MAE, R²) "
        "and **feature importances** so the dashboard can render the full forecast panel "
        "in a single API call. "
        "Supported `station_id` values: DL001, MU001, BL001, HY001, CH001, KO001, PU001, AH001."
    ),
    tags=["forecast"],
    responses={
        status.HTTP_200_OK: {
            "description": "Forecast generated successfully.",
        },
        status.HTTP_404_NOT_FOUND: {
            "description": "The specified station_id is not recognised.",
        },
        status.HTTP_422_UNPROCESSABLE_ENTITY: {
            "description": "Invalid query parameters (e.g., horizon_hours out of range).",
        },
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "description": "Unexpected server error.",
        },
    },
)
async def get_forecast(
    station_id: str = Query(
        description=(
            "CPCB station identifier to generate a forecast for. "
            "Example: 'DL001' (Delhi – Anand Vihar). "
            "Call GET /api/v1/stations to retrieve the full station list."
        ),
        min_length=3,
        max_length=20,
        examples=["DL001"],
    ),
    horizon_hours: int = Query(
        default=72,
        ge=1,
        le=72,
        description="Forecast horizon in hours. Range: 1–72. Default: 72.",
    ),
    service: ForecastService = Depends(lambda: forecast_service),
) -> ForecastResponse:
    """Generate and return an AQI forecast from the Forecast service."""

    # Validate station existence (stub check; replace with DB lookup in Day N)
    if station_id not in _KNOWN_STATIONS:
        raise NotFoundError(
            message=f"Station '{station_id}' not found. Use GET /api/v1/stations for the full list.",
            detail={"station_id": station_id, "known_stations": sorted(_KNOWN_STATIONS)},
        )

    logger.info(
        "Forecast request",
        station_id=station_id,
        horizon_hours=horizon_hours,
    )

    return await run_in_threadpool(
        service.get_station_forecast,
        station_id=station_id,
        horizon_hours=horizon_hours,
    )
